image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: <your-registry-url>
  DOCKER_NAMESPACE: <your-registry-namespace>
  IMAGE_PULL_SECRET_NAME: mtrdivedevops
  OPENSHIFT_SERVICE_ACCOUNT: diveappagilerobot

  OPENSHIFT_URL: <your-openshift-url>
  OPENSHIFT_NAMESPACE: <your-openshift-namespace>
  
stages:
  - deploy

appagile-deploy:
  image: <your-openshift-image>
  stage: deploy
  tags:
  - run_docker
  script:
  - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN
  - oc project $OPENSHIFT_NAMESPACE
  
  - (oc patch dc <OPENSHIFT_DEPLOYMENT_CONFIG_NAME> -p '{"spec":{"template":{"spec":{"containers":[{"name":"case-requirement","livenessProbe":{"httpGet":{"path":"<endpoint to check health>","port":12004,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":2},"imagePullPolicy":"Always","startupProbe":{"httpGet":{"path":"<endpoint to check health>","port":12004,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":3,"periodSeconds":10,"successThreshold":1,"failureThreshold":3}}]}}}}')
  when: manual
